name: "Terraform Plan"

on:
  push:
    tags:
      - "plan-*"

permissions:
  id-token: write
  contents: read

env:
  TF_LOG: "INFO"
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_route53_zone_id: ${{ secrets.ROUTE53_ZONE_ID }}
  TF_VAR_github_pat: ${{ secrets.GHCR_PAT }}
  TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: environments/production
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.8.1"

      - name: Terraform Init
        run: terraform init

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Extract version number
        id: get_version
        run: echo "version=$(echo ${{ github.ref }} | sed -e 's|refs/tags/plan-||')" >> $GITHUB_ENV

      - name: Terraform Plan
        run: terraform plan -out=terraform.tfplan

      - name: Upload Terraform Plan to S3
        run: |
          aws s3 cp terraform.tfplan s3://humansa-terraform-state/plans/plan-${{ env.version }}.tfplan
          echo "Plan saved to S3 as plan-${{ env.version }}.tfplan"

      - name: Generate and Upload Plan Summary
        run: |
          terraform show -no-color terraform.tfplan > plan-summary.txt
          aws s3 cp plan-summary.txt s3://humansa-terraform-state/plans/plan-${{ env.version }}-summary.txt
          echo "::notice::Plan summary saved to S3 as plan-${{ env.version }}-summary.txt"